### ISSUE TITLE
[Question] Project status

### ISSUE THREAD

**Issue by rajikaimal** [react-admin-lte/react-admin-lte#20]
Hey, awesome work. I wanna know about the project status. Is this production ready ?

**Comment by KorySchneider** [comment]
Thanks! I'm not sure what you mean by production ready.

**Comment by rajikaimal** [comment]
By production ready I meant _'stable enough to use it in a real application'_ ?

**Comment by KorySchneider** [comment]
Right, I thought I was in a different repo where the question wouldn't really make sense; my mistake. I think @jonmpqts should answer this one as he is the primary maintainer.

**Comment by jonmpqts** [comment]
This package is being used in an internal product that I am developing. As such the most work has gone into making the components needed for that project and I've been filling other components in as I find time.

The current codebase has had quite a few changes to the api since the published 0.4.0 release. I'm planning to cut a 1.0 release in a few weeks that should include a majority of the components. After that I plan on maintaining backward compatibility of the api when it makes sense to do so. I would consider it production ready at that point.

**Comment by rajikaimal** [comment]
Cool, thanks @jonmpqts & @KorySchneider :tada:
